" フォーカス/非フォーカス時の透過設定
autocmd FocusGained * set transparency=230
autocmd FocusLost * set transparency=180

" カラースキーム、フォント指定
" colorscheme monokai
" set guifont=MigMix\ 1M\ Regular:h12:cSHIFTJIS
" set guifont=Ricty\ Diminished\ for\ Powerline:h12:cSHIFTJIS
" set guifont=HackGen\ Console\ NF:h12:cSHIFTJIS

" Ricty Diminishedを使う場合アンチエイリアスの設定が必要、下記でアンチエイリアスの設定となる
set renderoptions=type:directx,renmode:5

" UTF-8にしたときメニューが文字化けするのでしないよう設定
"source $VIMRUNTIME/delmenu.vim
"set langmenu=ja_jp.utf-8
"source $VIMRUNTIME/menu.vim

" メニューバーを非表示にする
set guioptions-=m
" ツールバーを非表示にする
set guioptions-=T
" 左右のスクロールバーを非表示にする
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L
" 水平スクロールバーを非表示にする
set guioptions-=b
