#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
autoload -Uz promptinit
promptinit
prompt clint

cd ~

# offline dictionary
function dict() {
    grep $1 ~/.dict/gene-utf8.txt -A 1 -wi --color
}

# my man
function myman() {
    echo "my commands"
    echo " - dict : offline English -> Japanese dictionary"
    echo " - myman : show this message"
}
myman

# toot toot!
alias tl='toot timeline -r -1'
alias fav='toot notifications | less'
alias post='toot post'


# 以下は末尾に配置すること。
# ~/.zshrc.localが存在するときはそちらでオーバーライド
[ -f ~/.zshrc.local ] && source ~/.zshrc.local
